name: chat_gpt
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <3.2.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.1.0
  freezed_annotation: ^2.2.0
  flutter_bloc: ^8.1.2
  bloc_concurrency: ^0.2.1
  sqflite: ^2.2.6
  path: ^1.8.3
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  google_sign_in: ^6.1.4
  firebase_messaging: ^14.6.3
  firebase_crashlytics: ^3.3.3
  go_router: ^8.1.0
  cloud_firestore: ^4.8.2
  path_provider: ^2.1.1
  connectivity: ^3.0.6
  intl: ^0.18.1
  flutter_svg: ^2.0.7
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  firebase_storage: ^11.2.6
  permission_handler: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/vector/
    - assets/vector/dark/
    - assets/vector/light/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          style: italic
          weight: 900
